apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: fatsecret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:KcYzfgWLBhLNb9XIfKw4G1nzYjNpMqOVjBph5i/A6Pl8kRcMC1QzkTmbRymHsq9xvBvJQmI9o6D9mD8BKB5NAEWvTYLfcw86g+mCwkwMtA==,iv:vXqksUl1kL9U5Kqya7hKvc9ezrqDJ/Pqne1mFCqW0eU=,tag:wirvKsLu/wes2xsqmfKMZA==,type:comment]
    CLIENT_ID: ENC[AES256_GCM,data:6duDHcvdtSxDzUkocM7U7EcEd9IOqdIBUeoZtrkJ0rE=,iv:ArSM4AvuzS21z/ckhYW88e/LSk3o+f1kG2pe6DfgGFQ=,tag:cVn/unUuOsKGtDYO+xMpHA==,type:str]
    #ENC[AES256_GCM,data:8UywAnkQ9ND8YSXX47a297nEUkUjIIZRZFifTDiwXdKT0XfbQRIdNxW18JBwCn53ftpAK0lQ1/7bJKNxT2AaQwKd+YNUW15MPo2nKcXFaMjeIg==,iv:bUy8LK4KCgDkH+FYm5YxierV/7V6fFcawDAnOZj+13Q=,tag:IGjGiCUUirtz76YOKxaETA==,type:comment]
    CLIENT_SECRET: ENC[AES256_GCM,data:ML2W2vAO443Tn3NXbaL1ONz90gC2qWaj8XhkJ0w0UiI=,iv:u6/lECrL+E4/0JKkcyWFy89ir9bDIx2l73zeNgDrodI=,tag:atiyAKTwzYfqGS7PbdlZYQ==,type:str]
    #ENC[AES256_GCM,data:/jrOsRgAO6V1NJF5HUqURJpu1HKEgr7NqJrGnzPI0IerSsUa/68JfRIVcn3/+V5lR5Z0oKzKy4xCd48nZFcSNDplxNId6POVima5,iv:zy+LKbCeZyFwAle85yk62yKqgJP6j/ovEY1nt2iifhs=,tag:2kXh3bP7uLc/VpAK0foypg==,type:comment]
    ACCESS_TOKEN: ENC[AES256_GCM,data:UwvzXKGSf31Kzi9vAwKtjEssjVr4QuCTo47rknvt5Rw=,iv:273vRpwDZ4KtoOLzhG0kTa44PH4dBe/GutODCk55aXg=,tag:Kcs26gQxbIRTybkLuOSvxg==,type:str]
    #ENC[AES256_GCM,data:dQ60fuT8teqe0Ner9opEL2dpZ2Qu+ybVedeBQzI17g8adDjSfLZpTgPHJ9BrzroQc9nw4izAYJ1h3Mvp7JPWoTzd5NXxwEZK6L6LQDQVixFQFQ==,iv:+5JNnFCnRk5V5p5jUrVi+URQgmsupj/msgHNE/sQkdE=,tag:d0/oZiunNRmss2bYukZwjw==,type:comment]
    ACCESS_TOKEN_SECRET: ENC[AES256_GCM,data:4ImsqRZsGrsy1QE1rG68+ucGIQ68GxTgNesaJ76YEkQ=,iv:jYLg8hUAizfMPTlXaeOX3aElAyq/IacdfWh/ENizRc8=,tag:X6wLemHnuXlsG6yXC23muQ==,type:str]
    #ENC[AES256_GCM,data:Dbi1YTTpEOulaGjCgG5WMEJY3+OxXONB7WCrE3lxL4gW595AZkQGVF8iG2tBMQ==,iv:gw2Fs0OoIe32MWL2XwtNy3xlIrC0pEIh96HIsQpb1Rk=,tag:7xyDQKjgjqNyNuFg+fY7QQ==,type:comment]
    AUTH_PASSWORD: ENC[AES256_GCM,data:lj7Q3YL+FRmCNYP7+UeBxD9vPurB+p3hMG94y7ELj+4=,iv:HDv7HlL+xA9Ozb94jSUHN5O0WidGG80o01zE6wCg4I0=,tag:+XPLVOXfmJTyxWyXNT62SQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvR3h2S0thRVFrL2tYM0c4
            dzhXSThNUzFON2t0aHI5am45a2I1ZTlnUHhBCi9yQzZxMUxPYjAvR1VmbEp6dkYv
            TjZtTHRka3dqbnJLOXRzVnlqVldKNTgKLS0tIGF4TFdoVi8vN0JZYm44T3NZR3kv
            Y1AyQ1EyQVYxODJKZW5IYzAzTHZTWEkKUE+XaqBaEIjojA9j7vYFv+MFumfJ7uw4
            ueSFRmj93Tqkrmc5FuS+FjpYj79vKXtwdJDQQSeE+MzSmNamL968nQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10d00xrpljw4cga37ad0gt7se4nsehp5uv8yy3grkfqygd4pzyffqj3gr46
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTitxdVpNNjdpajM5WFNp
            UWJLVkFjc0ZWL1dwWlVxdWU2dEZjN1ZUUUF3CjdxeENyaW92RkRQdTVoTXhMczRr
            NzZoTC83cE9wekw5dUNPcGlYUi8vQmcKLS0tIHhRNDRSQm9aUW8yQnZCeHh6WDFD
            anhGM3Q5OTFkQ05wQS9GeGlDeGtDTnMKnZAnR6bFJzQ1XUIh7SgL6/1XWNuBUHh+
            tlzufCodS7KfmBEpZO5vNdNABzUbdx2DQodRQQSDoilkQaQ3PBWuLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sh4gkd6vtq97pl0fwc43mfq5sh5f0a92t2zm8ktk5h3fln0cs43qfpgm3t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T20:52:17Z"
    mac: ENC[AES256_GCM,data:RrjeuELG5Xoroo7VUs7bRZx/sItElcu/Zb3n6Ps0jhUrwCIiv0e3jMH6yRDgvrdKMLcw/TSfXOL88HsnAPkPi5rqFGKfgLbMC66YU0wVLU98z9B9MGaksJj9IRoMaup7Ow6j5AL5bLCkJrop5SqjyRSc86BEdvalCfKGFW3kWlo=,iv:NBSe2xYSNXVnW8/gyxz9kV6VUq4S5a1EO3HYy5aRAWM=,tag:8+H5NPB1pFAGUzUYwO3l5w==,type:str]
    version: 3.13.3
---
apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:Ft/ajwCK+rgUE2nZMvn9x1yyrDaeOGvRMCljMMkN8ZU4d5RpNI8NBd7sDEivhZrujG15cj+kUlT3xSv4MQmtYPubA09L8YP0fHCyyFx1cr8eouprVX1nZmRVr6e1nmeSI7u4XTDGc3lVtUeYz5Us8ME4PnTDBTVAW6Ge8Oysz/YNubAcTwza6OFOXUvnlHYBv5tjWb/30aMSCDmahH5F2fLwt5rfV47m3WwWGgPN6IExoqcmoqZrzTt06yQtefAWBO2PdMEiC82jCeRG/DcVzIg/ZjjjecBs6viYMbJW7g1ILayiBJDVk+TZma0acajZGJaGSZQiasZwjW1jAQrn2JlYq5PsNExPn6cFlQ==,iv:xhWVMnYGzjEh1Yfzd7XsZhSSuNX+JcF5e7TrAVcKD6k=,tag:5MoggZBcJIsJJjDFGH+BzA==,type:str]
kind: Secret
metadata:
    name: ghcr-secret
    namespace: fatsecret
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvR3h2S0thRVFrL2tYM0c4
            dzhXSThNUzFON2t0aHI5am45a2I1ZTlnUHhBCi9yQzZxMUxPYjAvR1VmbEp6dkYv
            TjZtTHRka3dqbnJLOXRzVnlqVldKNTgKLS0tIGF4TFdoVi8vN0JZYm44T3NZR3kv
            Y1AyQ1EyQVYxODJKZW5IYzAzTHZTWEkKUE+XaqBaEIjojA9j7vYFv+MFumfJ7uw4
            ueSFRmj93Tqkrmc5FuS+FjpYj79vKXtwdJDQQSeE+MzSmNamL968nQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10d00xrpljw4cga37ad0gt7se4nsehp5uv8yy3grkfqygd4pzyffqj3gr46
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTitxdVpNNjdpajM5WFNp
            UWJLVkFjc0ZWL1dwWlVxdWU2dEZjN1ZUUUF3CjdxeENyaW92RkRQdTVoTXhMczRr
            NzZoTC83cE9wekw5dUNPcGlYUi8vQmcKLS0tIHhRNDRSQm9aUW8yQnZCeHh6WDFD
            anhGM3Q5OTFkQ05wQS9GeGlDeGtDTnMKnZAnR6bFJzQ1XUIh7SgL6/1XWNuBUHh+
            tlzufCodS7KfmBEpZO5vNdNABzUbdx2DQodRQQSDoilkQaQ3PBWuLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sh4gkd6vtq97pl0fwc43mfq5sh5f0a92t2zm8ktk5h3fln0cs43qfpgm3t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T20:52:17Z"
    mac: ENC[AES256_GCM,data:RrjeuELG5Xoroo7VUs7bRZx/sItElcu/Zb3n6Ps0jhUrwCIiv0e3jMH6yRDgvrdKMLcw/TSfXOL88HsnAPkPi5rqFGKfgLbMC66YU0wVLU98z9B9MGaksJj9IRoMaup7Ow6j5AL5bLCkJrop5SqjyRSc86BEdvalCfKGFW3kWlo=,iv:NBSe2xYSNXVnW8/gyxz9kV6VUq4S5a1EO3HYy5aRAWM=,tag:8+H5NPB1pFAGUzUYwO3l5w==,type:str]
    version: 3.13.3
