apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: fatsecret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:VTPfu397699el3kvrkn30y4DJEyLTDT66dhwnZjyo/jxZuy//Fo5DmYbZI0u1Al4FNpEO+Lj5xuodzj/4otKTiuHvkpNx2cq4TeAME47zQ==,iv:ydQSdTYIk5R/ysKpS2TswAk4QFeyMh5qbCnRKfMxCtI=,tag:qpLm6S2c617eB98T4Gcc9g==,type:comment]
    CLIENT_ID: ENC[AES256_GCM,data:eYkwfO9ivJFuTrZKHtWpD9acFor9MMhiUuAs5AvA//c=,iv:6QaR9OIgY0qgErbYnHyuT3T0ujuaxwgTiJ8bg90hnyA=,tag:2gNNBgkwcAakcjUWdwsMfQ==,type:str]
    #ENC[AES256_GCM,data:dUGOC/nu5+aPJkilLODDh8Qx2sl9pTFYNYOvKWk48XgULVEon9LWlDkAsf8spIqoaWPE/IUNNaDB2ZFeci98i9N4KTdeJCPRAeRmUeiScdo7nw==,iv:GucjFOYJzQF0Og+Rg9aCsNCgoxWTNze1lEPvlEQy+C4=,tag:BtroFCQ1crGdBsIHHCVAtw==,type:comment]
    CLIENT_SECRET: ENC[AES256_GCM,data:tTh11zY4RfZYCilb/cG1jDAuIlByuHSkBdZbaZf/hgI=,iv:b9Nq0GHmK3i+6d88tFHZ2lN5YO+T4nHl7hMlWY+EgxU=,tag:SzBOUIUlRMliCL5iNeOPwA==,type:str]
    #ENC[AES256_GCM,data:9tQkTg+mHoJh4FNibTU2I//7eKNNfBHKbnhgtamMV/TagIry2+u9q6ddIlrbda2jFLkRXnpLB9cQmqe8DTGUWPoreU8B+JFqAtUV,iv:c3kzNpbaVQ8C5lW1of/iSeBB5u5r+uZzAxb17wqqaJE=,tag:2aV82BLhtYdwDG4TTjWxlg==,type:comment]
    ACCESS_TOKEN: ENC[AES256_GCM,data:bU27zqTGhUoy9qRkimBLpI/AjvLA5nYNYl6aZgVGoCM=,iv:bWEkilfzMQyyfHfElFp63xpVoiBIcmF9338vjh2Gih4=,tag:5RXniSFMN8Kr9PG1toADJw==,type:str]
    #ENC[AES256_GCM,data:FXXPHFEbW5DwxyVHmM4aU6MX6g0+K1rXjpj6YPK0G3Uz+DfisPWgRwAcFVblWPi1oUaWTC/MKnX2Z6hKblTizIXUCApGYi4HrsTa0ARb2UlF4w==,iv:DMzX6W+unqH9cUjINBRD0FT/eF6QcHYVJ31Da7yXwfk=,tag:pVIK3M4rdRMZ7HoFasldPA==,type:comment]
    ACCESS_TOKEN_SECRET: ENC[AES256_GCM,data:T9aUs199InIbLyqeUWC107n/e0dVNM55VImqtuxzh9E=,iv:/z7GdZqzy2nXrD4/RZYWYC38c/Y3+4BzoL2t7/Wr6NM=,tag:QiLwMxH3LLwTWtH2zl5BYA==,type:str]
    #ENC[AES256_GCM,data:ud9730OEQe8NhjFOH1EfIojM8JV0mEqJVcDF9S5upkIuXy3bCHu7BYnxAjOnOQ==,iv:+nmXzNfRXiJBrQLwwb+6M87mQtdDGnueafTbbTrGPuo=,tag:fEw4qls/B6YKkQIFaBcJ+g==,type:comment]
    AUTH_PASSWORD: ENC[AES256_GCM,data:AsmhdqB3yBtOQSP634nRVdfmPetWeLqAmrCKA4hUqOQ=,iv:mOtnrRtruAZ8AlIEVormkEzzN0unk4cQekFBt9BySyc=,tag:tviIw1Myz2yXR0TeHIsVwg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ejJUaTIzbWEyR2VGbXEw
            cGlKZlF0akxvcHo5UG52TFpWTHVqclRHZFZvCmx3dVhQbU81UUZzOUJJZkpDeHpt
            TFFrR3U1aENxRS9BSDE5ZHFGdHNwZ0UKLS0tIFRNUXJkTVlIY2lMZ1E2Y1pxQTRS
            dmZlQ3A2WlBQbjFuZStOR3gwSUxTcDgKlmUBmyAMfmsoOs3vjXslJ1ct9h1v6uwy
            mSrrhEQEejrXGzOflEwpM2+x0YqzoNZIQKBogDJB5goK1TvR0tZedA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10d00xrpljw4cga37ad0gt7se4nsehp5uv8yy3grkfqygd4pzyffqj3gr46
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRitTZElVT1BvSHRVWE1k
            aDdRcVBrQ3V0amRDNmxXRlI0UThaWng2VVJzCjZBK013TndBMnEzZVFjekM3U0Vi
            dm13bm5RRVcvL0V0em9TbDJNaSsySmsKLS0tIDFtdWJBQWxNUUlCZWV0aFV4bEZN
            a0VEeng0bURKZU9KNElrbHQ5VXNDMGMKFI89PV3wQoB4DIuhkr9SUdpBAAt/6Vom
            duLFgbo6bHL0wOaol+6OwewWmX1xym5de0WbCiRxjg1HiI40GOxwTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sh4gkd6vtq97pl0fwc43mfq5sh5f0a92t2zm8ktk5h3fln0cs43qfpgm3t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T21:35:02Z"
    mac: ENC[AES256_GCM,data:Z6XY93g0Gh6h1cBesiNgYoz5EQH8Ln9qf1yxFtXW1geUUfI+04Sl0xm68moQeeF15VAsBRW07lpJfepG88Q1OqAqMipAgOsNz5pkIk7rkXDIWn+Gu0bACcfwbfFQWjZ4nBJVD0onk20wn2mzfbcgs69MOvm+YO0GT3jMN8nzfdA=,iv:OiONK3m6go+OmSzBFe3UaRz9s79G1wAOP6a1rWZbbmo=,tag:powcRwF4fHA53ENjsRUFdQ==,type:str]
    version: 3.13.3
---
apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:zcgxPB5qgXUdoEWrZDLGPno2AM8igUQTCjq+uOEW97F6S7xrs1WZ/lhU6pQNx4CvJ+iB+lubq+Y8pqXGfEROoYjKN69DTytcds3dMxxHCFfSohd8arQYufw0VTP9itgbU+f4aDNaEonBZVGLeenj+89U7a3c5D+mkdobCIq7XGk5p+6ue4y0kq31OsfLHwLgKeRTm8SEpVBSNnBcFGp9Stx6l+BH3F97QItS5y0OAhJti8UXtkRCdne2dtWyjRMeNUGCWKVOaxPxqw+BKxPXVpLmF0e0JuDmCpm7A7mZ/ydXmsGXUUZkt5p2lm+1msutxgyFjEcRCdMWhn+KHHKxIJwvzupeu5blubmgSQ==,iv:bFvtqVj4oFqS/ExAF9LQEciFTDTXzVRV9FI9vjkDUhY=,tag:1LVJJ5VVaos3WDRbjx8+eQ==,type:str]
kind: Secret
metadata:
    name: ghcr-secret
    namespace: fatsecret
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ejJUaTIzbWEyR2VGbXEw
            cGlKZlF0akxvcHo5UG52TFpWTHVqclRHZFZvCmx3dVhQbU81UUZzOUJJZkpDeHpt
            TFFrR3U1aENxRS9BSDE5ZHFGdHNwZ0UKLS0tIFRNUXJkTVlIY2lMZ1E2Y1pxQTRS
            dmZlQ3A2WlBQbjFuZStOR3gwSUxTcDgKlmUBmyAMfmsoOs3vjXslJ1ct9h1v6uwy
            mSrrhEQEejrXGzOflEwpM2+x0YqzoNZIQKBogDJB5goK1TvR0tZedA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10d00xrpljw4cga37ad0gt7se4nsehp5uv8yy3grkfqygd4pzyffqj3gr46
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRitTZElVT1BvSHRVWE1k
            aDdRcVBrQ3V0amRDNmxXRlI0UThaWng2VVJzCjZBK013TndBMnEzZVFjekM3U0Vi
            dm13bm5RRVcvL0V0em9TbDJNaSsySmsKLS0tIDFtdWJBQWxNUUlCZWV0aFV4bEZN
            a0VEeng0bURKZU9KNElrbHQ5VXNDMGMKFI89PV3wQoB4DIuhkr9SUdpBAAt/6Vom
            duLFgbo6bHL0wOaol+6OwewWmX1xym5de0WbCiRxjg1HiI40GOxwTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sh4gkd6vtq97pl0fwc43mfq5sh5f0a92t2zm8ktk5h3fln0cs43qfpgm3t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T21:35:02Z"
    mac: ENC[AES256_GCM,data:Z6XY93g0Gh6h1cBesiNgYoz5EQH8Ln9qf1yxFtXW1geUUfI+04Sl0xm68moQeeF15VAsBRW07lpJfepG88Q1OqAqMipAgOsNz5pkIk7rkXDIWn+Gu0bACcfwbfFQWjZ4nBJVD0onk20wn2mzfbcgs69MOvm+YO0GT3jMN8nzfdA=,iv:OiONK3m6go+OmSzBFe3UaRz9s79G1wAOP6a1rWZbbmo=,tag:powcRwF4fHA53ENjsRUFdQ==,type:str]
    version: 3.13.3
